name: flutter unit test/ widget test

on:
  push:
    branches: [ main ]
  pull_request: [ main ]

jobs:
  build:
    run-on: ubunto-latest

    steps: 
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.0'

      - name: Install Flutter dependencies
        run: flutter pub get

      - name: Analyze flutter
        run: flutter Analyze
      
      - name: test
        run: flutter test

      - name: build apk
        run: flutter build apk --debug
      
